from __future__ import annotations

ROLLING_RESPONSE_EXAMPLE: dict[str, object] = {
    "source_service": "lotus-risk",
    "input_mode": "stateful",
    "scope": {
        "as_of_date": "2026-03-31",
        "reporting_currency": "USD",
        "net_or_gross": "NET",
    },
    "results": {
        "YTD": {
            "start_date": "2026-01-01",
            "end_date": "2026-03-31",
            "series_count": 64,
            "benchmark_series_count": 64,
            "aligned_benchmark_series_count": 64,
            "window_lengths_requested": [21],
            "window_count_requested": 1,
            "window_lengths_emitted": [21],
            "window_count_emitted": 1,
            "benchmark_context": {
                "requested": True,
                "available": True,
                "aligned": True,
                "reason": "APPLIED",
            },
            "risk_free_series_count": 0,
            "aligned_risk_free_series_count": 0,
            "risk_free_context": {
                "requested": False,
                "available": False,
                "aligned": False,
                "reason": "NOT_REQUESTED",
            },
            "window_results": [
                {
                    "window_length": 21,
                    "metric_summaries": {
                        "ROLLING_VOLATILITY": {
                            "total_point_count": 64,
                            "computed_point_count": 44,
                            "coverage_ratio": 0.6875,
                            "min_observations_required": 21,
                            "warmup_point_count": 20,
                            "non_computed_point_count": 20,
                            "post_warmup_gap_point_count": 0,
                            "latest_observation_date": "2026-03-31",
                            "latest": 0.12538011,
                            "average": 0.11844792,
                            "minimum": 0.09122408,
                            "maximum": 0.16651142,
                            "p05": 0.09540187,
                            "p50": 0.11793054,
                            "p95": 0.15541828,
                        },
                        "ROLLING_BETA": {
                            "total_point_count": 64,
                            "computed_point_count": 44,
                            "coverage_ratio": 0.6875,
                            "min_observations_required": 21,
                            "warmup_point_count": 20,
                            "non_computed_point_count": 20,
                            "post_warmup_gap_point_count": 0,
                            "latest_observation_date": "2026-03-31",
                            "latest": -0.08222479,
                            "average": 0.04185233,
                            "minimum": -0.32108851,
                            "maximum": 0.41862514,
                            "p05": -0.24148062,
                            "p50": 0.05739184,
                            "p95": 0.31680427,
                        },
                        "ROLLING_TRACKING_ERROR": {
                            "total_point_count": 64,
                            "computed_point_count": 44,
                            "coverage_ratio": 0.6875,
                            "min_observations_required": 21,
                            "warmup_point_count": 20,
                            "non_computed_point_count": 20,
                            "post_warmup_gap_point_count": 0,
                            "latest_observation_date": "2026-03-31",
                            "latest": 0.09793316,
                            "average": 0.08741941,
                            "minimum": 0.05266133,
                            "maximum": 0.12807142,
                            "p05": 0.05824015,
                            "p50": 0.08653728,
                            "p95": 0.12150684,
                        },
                    },
                    "metric_series_context": {
                        "requested": False,
                        "included": False,
                        "emitted_point_count": 0,
                        "reason": "OMITTED_BY_REQUEST",
                    },
                    "metric_series": None,
                }
            ],
            "quality_flags": [],
            "error": None,
        }
    },
    "metadata": {
        "contract_version": "v1",
        "methodology_version": "rolling_metrics.v1",
        "annualization_basis": 252,
        "metric_unit_semantics": {
            "ROLLING_VOLATILITY": "decimal_ratio",
            "ROLLING_BETA": "unitless",
            "ROLLING_TRACKING_ERROR": "decimal_ratio",
        },
        "requested_metrics": [
            "ROLLING_VOLATILITY",
            "ROLLING_BETA",
            "ROLLING_TRACKING_ERROR",
        ],
        "window_lengths_requested": [21],
        "window_count_requested": 1,
        "alignment_policy": "INNER_JOIN",
        "min_observations_policy": "STRICT",
        "include_time_series": False,
        "benchmark_context": {
            "requested": True,
            "requested_metrics": [
                "ROLLING_BETA",
                "ROLLING_TRACKING_ERROR",
            ],
        },
        "risk_free_context": {
            "requested": False,
            "requested_metrics": [],
        },
    },
}
