from __future__ import annotations

UNKNOWN_UPSTREAM_OPERATION = "unknown"

LOTUS_CORE_CREATE_SIMULATION_SESSION_OPERATION = "/simulation-sessions"
LOTUS_CORE_ADD_SIMULATION_CHANGES_OPERATION = "/simulation-sessions/{session_id}/changes"
LOTUS_CORE_SNAPSHOT_OPERATION = "/integration/portfolios/{portfolio_id}/core-snapshot"
LOTUS_CORE_INSTRUMENT_ENRICHMENT_OPERATION = "/integration/instruments/enrichment-bulk"
LOTUS_CORE_POSITION_TIMESERIES_OPERATION = (
    "/integration/portfolios/{portfolio_id}/analytics/position-timeseries"
)
LOTUS_CORE_RISK_FREE_SERIES_OPERATION = "/integration/reference/risk-free-series"
LOTUS_CORE_RISK_FREE_COVERAGE_OPERATION = "/integration/reference/risk-free-series/coverage"

LOTUS_PERFORMANCE_RETURNS_SERIES_OPERATION = "/integration/returns/series"
LOTUS_PERFORMANCE_RETURNS_SERIES_STATUS_OPERATION = (
    "/integration/returns/series/status/{calculation_id}"
)
LOTUS_PERFORMANCE_RETURNS_SERIES_RESULT_OPERATION = (
    "/integration/returns/series/results/{calculation_id}"
)
LOTUS_PERFORMANCE_BENCHMARK_EXPOSURE_CONTEXT_OPERATION = "/integration/benchmarks/exposure-context"

UPSTREAM_OPERATION_VALUES: frozenset[str] = frozenset(
    {
        LOTUS_CORE_CREATE_SIMULATION_SESSION_OPERATION,
        LOTUS_CORE_ADD_SIMULATION_CHANGES_OPERATION,
        LOTUS_CORE_SNAPSHOT_OPERATION,
        LOTUS_CORE_INSTRUMENT_ENRICHMENT_OPERATION,
        LOTUS_CORE_POSITION_TIMESERIES_OPERATION,
        LOTUS_CORE_RISK_FREE_SERIES_OPERATION,
        LOTUS_CORE_RISK_FREE_COVERAGE_OPERATION,
        LOTUS_PERFORMANCE_RETURNS_SERIES_OPERATION,
        LOTUS_PERFORMANCE_RETURNS_SERIES_STATUS_OPERATION,
        LOTUS_PERFORMANCE_RETURNS_SERIES_RESULT_OPERATION,
        LOTUS_PERFORMANCE_BENCHMARK_EXPOSURE_CONTEXT_OPERATION,
        UNKNOWN_UPSTREAM_OPERATION,
    }
)


__all__ = [
    "LOTUS_CORE_ADD_SIMULATION_CHANGES_OPERATION",
    "LOTUS_CORE_CREATE_SIMULATION_SESSION_OPERATION",
    "LOTUS_CORE_INSTRUMENT_ENRICHMENT_OPERATION",
    "LOTUS_CORE_POSITION_TIMESERIES_OPERATION",
    "LOTUS_CORE_RISK_FREE_COVERAGE_OPERATION",
    "LOTUS_CORE_RISK_FREE_SERIES_OPERATION",
    "LOTUS_CORE_SNAPSHOT_OPERATION",
    "LOTUS_PERFORMANCE_BENCHMARK_EXPOSURE_CONTEXT_OPERATION",
    "LOTUS_PERFORMANCE_RETURNS_SERIES_OPERATION",
    "LOTUS_PERFORMANCE_RETURNS_SERIES_RESULT_OPERATION",
    "LOTUS_PERFORMANCE_RETURNS_SERIES_STATUS_OPERATION",
    "UNKNOWN_UPSTREAM_OPERATION",
    "UPSTREAM_OPERATION_VALUES",
]
