"""Generate report-only enterprise refactor quality evidence for lotus-risk."""

from __future__ import annotations

import ast
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
QUALITY_DIR = ROOT / "quality"
SRC_DIR = ROOT / "src"
TESTS_DIR = ROOT / "tests"


@dataclass(frozen=True)
class FileSize:
    path: str
    lines: int
    bytes: int


@dataclass(frozen=True)
class SymbolSize:
    path: str
    name: str
    kind: str
    lines: int


def _python_files(base: Path) -> list[Path]:
    return sorted(path for path in base.rglob("*.py") if "__pycache__" not in path.parts)


def _relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _run(command: list[str]) -> tuple[int, str]:
    try:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
    except FileNotFoundError as exc:
        return 127, str(exc)
    return completed.returncode, completed.stdout.strip()


def collect_file_sizes() -> list[FileSize]:
    sizes: list[FileSize] = []
    for path in _python_files(SRC_DIR) + _python_files(TESTS_DIR):
        text = path.read_text(encoding="utf-8")
        sizes.append(FileSize(path=_relative(path), lines=len(text.splitlines()), bytes=len(text)))
    return sorted(sizes, key=lambda item: (item.lines, item.bytes), reverse=True)


def collect_symbol_sizes() -> list[SymbolSize]:
    sizes: list[SymbolSize] = []
    for path in _python_files(SRC_DIR):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                end_lineno = getattr(node, "end_lineno", node.lineno)
                sizes.append(
                    SymbolSize(
                        path=_relative(path),
                        name=node.name,
                        kind=type(node).__name__,
                        lines=end_lineno - node.lineno + 1,
                    )
                )
    return sorted(sizes, key=lambda item: item.lines, reverse=True)


def count_route_decorators() -> int:
    main_path = SRC_DIR / "app" / "main.py"
    return sum(
        1 for line in main_path.read_text(encoding="utf-8").splitlines() if line.startswith("@app.")
    )


def command_status(command: list[str]) -> str:
    returncode, output = _run(command)
    output_lines = output.splitlines()
    selected_lines = output_lines[:6]
    if len(output_lines) > 12:
        selected_lines.extend(["..."])
        selected_lines.extend(output_lines[-6:])
    elif len(output_lines) > 6:
        selected_lines = output_lines
    excerpt = "\n".join(selected_lines)
    status = "passed" if returncode == 0 else f"reported exit {returncode}"
    if not excerpt:
        return status
    return f"{status}\n\n```text\n{excerpt}\n```"


def collected_test_count(evidence: str) -> str:
    match = re.search(r"(\d+) tests collected", evidence)
    if match is None:
        return "unknown"
    return match.group(1)


def markdown_table(headers: tuple[str, ...], rows: list[tuple[object, ...]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(str(value) for value in row) + " |" for row in rows)
    return "\n".join(lines)


def write_baseline_report(
    file_sizes: list[FileSize],
    symbol_sizes: list[SymbolSize],
    unit_collection_evidence: str,
) -> None:
    route_count = count_route_decorators()
    text = f"""# Lotus Risk Enterprise Refactor Baseline

Generated by `python scripts/generate_quality_baseline.py`.

## Scope

This is the initial report-only baseline for the enterprise refactor program. It captures measurable
current-state risk in code size, API-entry-point modularity, architectural governance, tool coverage,
documentation posture, and validation gates. It is not a completion claim.

## Code Size Baseline

- Python source files under `src/`: {len(_python_files(SRC_DIR))}
- Python test files under `tests/`: {len(_python_files(TESTS_DIR))}
- API entry point route/middleware/handler decorators in `src/app/main.py`: {route_count}

### Largest Python Files

{markdown_table(("Path", "Lines", "Bytes"), [(item.path, item.lines, item.bytes) for item in file_sizes[:20]])}

### Largest Functions And Classes

{markdown_table(("Path", "Symbol", "Kind", "Lines"), [(item.path, item.name, item.kind, item.lines) for item in symbol_sizes[:20]])}

## Tool Baseline

- Ruff: configured in `pyproject.toml`; enforced by `make lint`.
- mypy: configured in `mypy.ini`; enforced by `make typecheck`.
- pytest/coverage: repo-native test commands exist; PR coverage floor remains 98%.
- pip-audit: enforced through `make security-audit`.
- Bandit, radon, vulture, deptry, import-linter, and interrogate are now declared as development
  tooling for progressive quality evidence.
- Spectral config is present for OpenAPI governance; CI is report-only until generated OpenAPI
  export is standardized for this repository.

## Current Architectural Findings

1. `src/app/main.py` now preserves the stable ASGI export while `src/app/app_factory.py` owns
   FastAPI app construction, middleware registration, exception-handler registration, and router
   registration. Standard OpenAPI error metadata now lives in `src/app/api_errors.py`; health, readiness,
   metrics, operational diagnostics, trust telemetry, and capability publication now live in
   `src/app/routers/operational.py`; stateless source-product endpoints now live in
   `src/app/routers/source_products.py`; the primary risk calculation endpoint now lives in
   `src/app/routers/risk_calculation.py`; drawdown analytics now lives in
   `src/app/routers/drawdown.py`; rolling metrics now lives in `src/app/routers/rolling.py`;
   concentration analytics now lives in `src/app/routers/concentration.py`; historical
   attribution analytics now lives in `src/app/routers/historical_attribution.py`.
2. Operational, capability, stateless source-product, and core calculation routes are split into
   router modules. Downstream client resolution now lives in `src/app/dependencies/downstream_clients.py`
   so routers no longer import `src/app/integrations` adapters directly.
3. Business calculations already live mostly under `src/app/services`, which gives the next slices
   a workable extraction boundary.
4. Infrastructure clients already sit under `src/app/integrations`, and API routes now access them
   through the application dependency provider boundary.
5. Consistent error envelopes exist through `app.error_response`, but the contract remains
   repository-local rather than full RFC 7807 problem-details.

## OpenAPI And API Governance Gaps

1. Operation IDs are not yet visibly standardized in route decorators.
2. Pagination/filtering/sorting governance is not broadly applicable to calculation POST endpoints,
   but any future list/read-model route must use an explicit shared contract.
3. Health, liveness, readiness, metadata, metrics, and ops endpoints exist and are documented, but
   public/internal route grouping is not yet enforced by module structure.
4. Standard error response metadata exists in `src/app/api_errors.py`, but route-level examples
   should be certified after router extraction.

## Security And Resilience Gaps

1. Enterprise audit middleware and correlation middleware are present.
2. Sensitive-data redaction has unit coverage.
3. Upstream error mapping is centralized through `app.upstream_errors`.
4. Timeout, retry, and pooling posture should be made explicit in quality docs for each downstream
   adapter.
5. API abuse controls beyond payload size and authorization headers need explicit threat-model
   evidence before enterprise-readiness enforcement.

## Observability Gaps

1. HTTP, endpoint execution, supportability, and freshness metrics exist.
2. Metrics label bounds are tested for RFC-0108 supportability.
3. Trace/correlation propagation exists through middleware, but route extraction should preserve
   the propagation contract in tests.
4. Operational dashboards and alert contracts are documented locally only where previous RFCs
   required them; this refactor program needs a consolidated observability page.

## Documentation Gaps

The repository has deep domain-methodology documentation and domain API pages. The refactor program
still needs consolidated enterprise pages for architecture, API governance, observability, security,
operations, and supported features. Initial pages are added in this slice.

## Validation Snapshot

- Unit test collection: {unit_collection_evidence}
- Import-linter report-only: {command_status(["lint-imports", "--config", ".importlinter"])}
"""
    (QUALITY_DIR / "baseline_report.md").write_text(text, encoding="utf-8")


def write_health_reports(
    file_sizes: list[FileSize],
    symbol_sizes: list[SymbolSize],
    unit_collection_evidence: str,
) -> None:
    main_lines = next(item.lines for item in file_sizes if item.path == "src/app/main.py")
    unit_tests_collected = collected_test_count(unit_collection_evidence)
    scorecard = f"""# Lotus Risk Quality Scorecard

| Dimension | Current posture | Refactor target |
| --- | --- | --- |
| API modularity | `src/app/main.py` is {main_lines} lines | Split app factory, routers, error metadata, and dependencies |
| Service boundaries | Calculation engines are under `src/app/services` | Keep business logic out of routers and middleware |
| Architecture enforcement | `.importlinter` report-only contracts added | Promote to CI gate after router extraction |
| OpenAPI governance | Existing repo gate plus Spectral config added | Standardize operation IDs and generated OpenAPI lint |
| Tests | {len(_python_files(TESTS_DIR))} Python test files; {unit_tests_collected} unit tests collect | Add route-boundary and governance regression tests per slice |
| Security | pip-audit gate exists; Bandit configured | Add report-only Bandit evidence, then enforce new regressions |
| Observability | Metrics/correlation support exists | Consolidate runbook and dashboard/alert evidence |
"""
    (QUALITY_DIR / "quality_scorecard.md").write_text(scorecard, encoding="utf-8")

    health = f"""# Lotus Risk Refactor Health Report

## Current Slice

This slice establishes the report-only enterprise quality baseline and progressive gate scaffolding.

## Highest Priority Refactor Targets

{
        markdown_table(
            ("Rank", "Target", "Evidence", "Next action"),
            [
                (
                    1,
                    "API entry point",
                    f"src/app/main.py has {main_lines} lines and {count_route_decorators()} app decorators",
                    "Extract routers and dependency providers",
                ),
                (
                    2,
                    "Concentration module",
                    "Largest service and contract files are concentration-related",
                    "Split source resolution, issuer aggregation, and response assembly",
                ),
                (
                    3,
                    "Risk calculation engine",
                    f"Largest function is {symbol_sizes[0].name} at {symbol_sizes[0].lines} lines",
                    "Extract per-metric calculators behind stable service API",
                ),
            ],
        )
    }

## Progressive Gate Posture

1. Baseline/report-only: active in this slice.
2. Fail only new regressions: next stage after baseline artifacts are stable.
3. Enforce agreed thresholds: after monolithic routers and largest engines are reduced.
4. Enterprise-readiness gates: final stage once API, security, observability, and docs are certified.
"""
    (QUALITY_DIR / "refactor_health_report.md").write_text(health, encoding="utf-8")


def write_rules() -> None:
    (QUALITY_DIR / "architecture_rules.md").write_text(
        """# Lotus Risk Architecture Rules

1. Routers call application services or use cases only.
2. Routers must not call repository, database, HTTP, Kafka, Redis, or downstream adapter APIs directly.
3. Middleware stays thin and business-logic-free.
4. Domain and service modules must not depend on FastAPI, Starlette request/response objects, or
   infrastructure transport models.
5. Infrastructure adapters sit behind narrow service-facing protocols.
6. DTO contracts and persistence/transport models must not leak into domain calculation logic.
7. Downstream errors map through `app.upstream_errors` and API errors map through the standard
   error response envelope.
8. Every request must support and propagate correlation identity.
9. Logs and metrics must use bounded labels and must not expose portfolio, client, trace,
   correlation, request-body, or response-body values as labels.
""",
        encoding="utf-8",
    )
    (QUALITY_DIR / "api_governance_rules.md").write_text(
        """# Lotus Risk API Governance Rules

1. Every endpoint must define summary, description, tags, response model, operation ID, examples,
   and standard error responses.
2. POST calculation endpoints must document input mode, source ownership, lineage, supportability,
   and failure semantics.
3. Any list endpoint must use consistent pagination, filtering, and sorting contracts before
   publication.
4. Health, liveness, readiness, metrics, operational, internal, and public analytics endpoints must
   remain separated in code and documentation.
5. Deprecation must be explicit in OpenAPI and supported-feature documentation.
6. RFC-0067 vocabulary and no-alias gates remain mandatory.
""",
        encoding="utf-8",
    )


def main() -> int:
    QUALITY_DIR.mkdir(exist_ok=True)
    file_sizes = collect_file_sizes()
    symbol_sizes = collect_symbol_sizes()
    unit_collection_evidence = command_status(
        ["python", "-m", "pytest", "tests/unit", "--collect-only", "-q"]
    )
    write_baseline_report(file_sizes, symbol_sizes, unit_collection_evidence)
    write_health_reports(file_sizes, symbol_sizes, unit_collection_evidence)
    write_rules()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
